
spring:
  application:
    name: micro-service-i

  datasource:
    initialization-mode: embedded
    schema: classpath:database/schema-h2.sql
    data: classpath:database/data-h2.sql
    platform: all

  liquibase:
    enabled: true

#mybatis:
#  type-aliases-package: com.shaun.microservice.microservicei.entity
#  mapper-locations: classpath:/com.shaun.microservice.microservicei/mapper/*
#  configuration:
#    mapUnderscoreToCamelCase: true

server:
  port: 8801

camel:
  springboot:
    name: camel-service-i
greeting: Hello World

timer.period: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    enabled: false
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
hawtio:
  authenticationEnabled: false


logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log


feign:
  hystrix:
    enabled: true
