
server:
  port: 8802

spring:
  application:
    name: micro-service-ii

  datasource:
    initialization-mode: embedded
    schema: classpath:database/schema-h2.sql
    data: classpath:database/data-h2.sql
    platform: all
    url: jdbc:h2:file:./database/h2/uaa  #h2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
  file:
    name: ./logs/${spring.application.name}.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    enabled: false
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}