setting:
  lock-based-concurrent-control:
    connect-type: redis
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 0
      password:
      database: 2
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
        registry-key: mutex
        expire-after: 60000
    jdbc:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://49.235.155.249:3306/smart_office_welink?serverTimezone=Hongkong&characterEncoding=UTF-8&useSSL=false
      username: root
      password: HJSY.aifm
    zookeeper:
      root-path: /zookeeper/mutex
      curator:
        retry-count:
        elapsed-time-ms:
        connect-string:
        session-timeout-ms:
        connection-timeout-ms:
