setting:
  lock-based-concurrent-control:
    connect-type: jvm
    redis:
      host:
      port:
      timeout:
      password:
      database:
      jedis:
        pool:
          max-active:
          max-wait:
          max-idle:
          min-idle:
        registry-key: mutex
        expire-after: 60000
    jdbc:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://49.235.155.249:3306/smart_office_welink?serverTimezone=Hongkong&characterEncoding=UTF-8&useSSL=false
      username: root
      password: HJSY.aifm
    zookeeper:
      root-path: /zookeeper/mutex
      curator:
        retry-count:
        elapsed-time-ms:
        connect-string:
        session-timeout-ms:
        connection-timeout-ms:
