setting:
  lock-based-concurrent-control:
    connect-type: jvm
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 0
      password:
      database: 2
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
        registry-key: mutex
        expire-after: 60000
    jdbc:
      driverClassName:
      url:
      username:
      password:
    zookeeper:
      root-path: /zookeeper/mutex
      curator:
        retry-count:
        elapsed-time-ms:
        connect-string:
        session-timeout-ms:
        connection-timeout-ms:
