server:
  port: 8783
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: uaa-spring-security-login
  profiles:
    active: '@spring.profiles.active@'

logging:
  level:
    root: info
  file:
    name: ./logs/${spring.application.name}.log

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    enabled: false
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}